### PR TITLE
Data correction issue6 new

### LINKED ISSUE #6: Script outputs false data for stations not in model domain
If the generateComputedMatlab script is asked to generate a timeseries for a station outside of the model domain, it will calculate the RoCo of the station, and then change that to the max row and/or max col of the grid. If the new RoCo is an active cell, the script will then output a timeseries for that location. This incorrectly gives the impression that data is being generated for stations outside of the model grid.
The problem occurs in the following location:
generateComputedMatlab.m calls extractComputedData.m which calls readMSHE_WM.m.
readMSHE_WM.m lines 51-54:
```
        x_i = min(TS.S.XCount,STATION.i + 1);
        y_j = min(TS.S.YCount,STATION.j + 1);
        x_i = max(0,x_i);
        y_j = max(0,y_j);

```
These lines take the row and column of any station outside the greater square box domain and changes them to be the max row or col, or 0. So the script will generate model results for stations outside the domain without generating a warning or error.

The solution we need to implement is to create a function that reads the model's domain dfs2 file into an array in the INI variable, then checks each station's RoCo to determine if it is in an active cell. Stations not meeting this criteria can have their RoCo set to 0,0.

### PR DESCRIPTION
**Pull request by LAGO-Support**
Was trying to perform the I and J value checks on all lines, including the M11 data that has empty values. Added a line to check if xls row is MSHE data before performing I and J value checks.

### CODE REVIEW

**Comment by kirenbahm** [comment]
This looks like the problem is fixed. However, the warning message is a little confusing:

`Warning: Station NP201 at excel row 470 with a coordinate indexes of (300 , 167) is estimated as (1.743037e+02 , 1.672059e+02) based on model domain dfs2`

Shouldn't the coordinates `(1.743037e+02 , 1.672059e+02)` be integers?

Let me know what you think should be done here.

Thanks.

**Comment by LAGO-Support** [comment]
Edited readFileCompCord to fix the scientific notation text in the warning

**Comment by kirenbahm** [comment]
This still doesn't seem right to me. For example, I am getting the following warning for a station in the middle of the model domain:
`--- Warning: Station NE2 at excel row 459 with a coordinate indexes of (215 , 167) is estimated as (216 , 168) based on model domain dfs2`

**Comment by LAGO-Support** [comment]
Made adjustment in I, J check to account for half cell offset in the preprocessed domain file

**Comment by kirenbahm** [comment]
This commit looks good and completes the task.

Because this branch and the master have diverged so much during the development of this feature, I decided to copy these edits from branch 'DataCorrectionIssue6-new' into a new-new branch called  'DataCorrectionIssue6-new-new'.  This was simpler to do cleanly instead of resolving the merge conflicts from this branch.

I will close this pull request without merging, and merge these edits into the master via the new-new branch.

Thanks for your work on this.

**Pull request closed without merging**
