### PR TITLE
Aggregate station data

### LINKED ISSUE #26: Aggregate Stations feature
AGGREGATE_STATIONS FEATURE

Create a new function that takes the timeseries (datatype is always flow) from a group of stations and aggregates the values to create a new station and timeseries.

For example:
`S332TOT_Q = 
[aggregate_rules_file_example.txt](https://github.com/kirenbahm/ENP_TOOLS/files/4617137/aggregate_rules_file_example.txt)
S332BN_Q + S332BW_Q + S332C_Q + S332D_Q`

This function will:

- [x] Read the aggregate_rules_file_example.txt from the DATA_COMMON directory (this contains the equations)
- [x] Check that the names of the new stations don't match any existing station names
- [x] Check that we are dealing with daily values
- [x] Check that all the equations have valid syntax
- [x] For stations that are subtracted, multiply the timeseries by (-1.0) before adding to the total
- [x] Aggregate the daily values according to the equations
 -print out the equations to the screen after calculating each one
 -if one of the summands does not exist, print out "(not found)" after the station name but continue the calculation without it
-if none of the summands exist, print out "(not calculated)" after the aggregate station name in addition to "(not found)" after the summands
 ie:  `S332TOT_Q = + S332BN_Q + S332BW_Q(not found) + S332C_Q + S332D_Q`
 ie:  `S332TOT_Q(not calculated) = + S332BN_Q(not found) + S332BW_Q(not found) + S332C_Q(not found) + S332D_Q(not found)`

- [x] Allow for new station totals to be used as summands in subsequent equations in the list
`S332TOT_Q = + S332BN_Q + S332BW_Q + S332C_Q + S332D_Q`
`AllPumps_Q = + S332TOT_Q + S199_Q + S200_Q`

### PR DESCRIPTION
**Pull request by LAGO-Support**
Reads in a text file for equations then create new stations in the database and adds aggregated data to them based on source equations.

### CODE REVIEW

**Comment by LAGO-Support** [comment]
If you could please review. If we need to add more actual data to some of the fields for the new Aggregated stations instead of null or empty values, let me know. We can discuss options for potential fillers.

**Comment by kirenbahm** [comment]
Overall this looks good. Thanks for cranking out this so quickly.

A few minor things to address:

1. Change function name and filename to match
2. Set `StationEqFile` in `ANALYSIS_COMPARE` as part of the `INI` variable
3. Add description of function at top of script
4. Please add more comments in the script describing what it's doing and what the variables stand for (double the amount of comments you have)
5. Improve the formatting for what gets printed to Standard Output (Command Window)
6. I have added some Bad stations to the `aggregate_rules_file_example-AGG.txt` and` STATIONS-test-short-AGG.txt` lists (attached). Try the script with these, and fix any errors that come up.

**Comment by kirenbahm** [comment]
And here are the attachments...
[STATIONS-test-short-AGG.txt](https://github.com/kirenbahm/ENP_TOOLS/files/4658206/STATIONS-test-short-AGG.txt)
[aggregate_rules_file_example-AGG.txt](https://github.com/kirenbahm/ENP_TOOLS/files/4658208/aggregate_rules_file_example-AGG.txt)

**Comment by LAGO-Support** [comment]
Addressed previous comments. Please review and if more changes are desired let us know.

**Comment by kirenbahm** [comment]
Everything is complete here except "2.  Set StationEqFile in ANALYSIS_COMPARE as part of the INI variable"

A couple of quick edits to ANALYSIS_COMPARE.m to declare and check for the INI.StationEqFile 
 should do the trick.

**Comment by kirenbahm** [comment]
I tried adding two new equations to the list, and am getting unexpected results.
The equations are:
```
L31Nin2 = S334_Q - S336_Q + S335_Q - S356_Q
L31N_lower_total = S331T_Q - S194_Q - S196_Q - S332T_Q - S174_Q - S176_Q

```
Here is the output:
```
----Parsing Equation
----L31Nin2 = S334_Q - S336_Q + S335_Q - S356_Q
----Assigning Aggregate Station ID: L31Nin2....Success.
----Checking Summand Station S334_Q...OK
----Checking Summand Station S336_Q...OK
----Checking Summand Station S335_Q...OK
----Checking Summand Station S356_Q...Not Flow
----Final Equation: L31Nin2 =  - S336_Q + S335_Q - S356_Q 

----Parsing Equation
----L31N_lower_total = S331T_Q - S194_Q - S196_Q - S332T_Q - S174_Q - S176_Q
----Assigning Aggregate Station ID: L31N_lower_total....Success.
----Checking Summand Station S331T_Q...OK
----Checking Summand Station S194_Q...OK
----Checking Summand Station S196_Q...OK
----Checking Summand Station S332T_Q...Not found
----Checking Summand Station S174_Q...Not Flow
----Checking Summand Station S176_Q...OK
----Final Equation: L31N_lower_total =  - S194_Q - S196_Q   - S174_Q - S176_Q 
```
So, for the first equation, the output says summand S334_Q is 'OK', yet it does not appear in the Final Equation.  Summand S356 is 'Not Flow' but is used in the Final Equation.

Can you figure out what's going on here?
Thanks!

**Comment by LAGO-Support** [comment]
S356_Q Error
S174_Q Error

Fixed the issue you reported. The final equation for calculation was correct but the not flow station removed the first station rather than the correct station from print out of the final equation.

The two not flow stations are set as Elevation datatype in the database.

The not found station may be a misspelling. S332T_Q doesn't exist, but S332TOT_Q was a new aggregate from a previous equation. Was this what you were refering to?

**Pull request merged**
